### ISSUE TITLE
Failed to open file '/var/lib/mysql//galera.cache': 1 (Operation not permitted)

### ISSUE THREAD

**Issue by ghatdev** [adfinis-sygroup/openshift-mariadb-galera#21]
I added priviliged scc to default service account.

Full log file is :
+ CONTAINER_SCRIPTS_DIR=/usr/share/container-scripts/mysql
--
  | + EXTRA_DEFAULTS_FILE=/etc/my.cnf.d/galera.cnf
  | + '[' -z dbcluster1 ']'
  | + echo 'Galera: Finding peers'
  | Galera: Finding peers
  | ++ hostname -f
  | ++ cut -d. -f2
  | Using service name: galera
  | + K8S_SVC_NAME=galera
  | + echo 'Using service name: galera'
  | + cp /usr/share/container-scripts/mysql/galera.cnf /etc/my.cnf.d/galera.cnf
  | + /usr/bin/peer-finder -on-start=/usr/share/container-scripts/mysql/configure-galera.sh -service=galera
  | 2018/07/16 19:04:10 Peer list updated
  | was []
  | now [mysql-0.galera.dbcluster1.svc.cluster.local]
  | 2018/07/16 19:04:10 execing: /usr/share/container-scripts/mysql/configure-galera.sh with stdin: mysql-0.galera.dbcluster1.svc.cluster.local
  | 2018/07/16 19:04:10
  | 2018/07/16 19:04:11 Peer finder exiting
  | + '[' '!' -d /var/lib/mysql/mysql ']'
  | + exec mysqld
  | 2018-07-16 19:04:11 140443185940736 [Note] mysqld (mysqld 10.1.31-MariaDB) starting as process 1 ...
  | 2018-07-16 19:04:11 140443185940736 [Note] WSREP: Read nil XID from storage engines, skipping position init
  | 2018-07-16 19:04:11 140443185940736 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib64/galera/libgalera_smm.so'
  | 2018-07-16 19:04:11 140443185940736 [Note] WSREP: wsrep_load(): Galera 25.3.22(r3764) by Codership Oy <info@codership.com> loaded successfully.
  | 2018-07-16 19:04:11 140443185940736 [Note] WSREP: CRC-32C: using hardware acceleration.
  | 2018-07-16 19:04:11 140443185940736 [Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1, safe_to_bootstrap: 1
  | 2018-07-16 19:04:11 140443185940736 [ERROR] WSREP: Failed to open file '/var/lib/mysql//galera.cache': 1 (Operation not permitted)
  | at galerautils/src/gu_fdesc.cpp:constructor_common():142
  | 2018-07-16 19:04:11 140443185940736 [ERROR] WSREP: wsrep::init() failed: 7, must shutdown
  | 2018-07-16 19:04:11 140443185940736 [ERROR] Aborting

How can I fix it?

**Comment by tongpu** [comment]
You shouldn't need to configure the privileged SCC, because the image is built to as an unprivileged use.
Are you using a PVC for persistent storage or what kind of storage are you using?

**Comment by ghatdev** [comment]
@tongpu I'm using NFS now.

**Comment by tongpu** [comment]
What NFS version are you using? `galera.cache` is a memory mapped file and according to https://stackoverflow.com/a/10375296 you would need at least NFSv4 for that.

**Comment by ghatdev** [comment]
@tongpu 
Flags:	rw,relatime,vers=4.1,rsize=1048576 ...
I think my nfs version is >4

**Comment by tongpu** [comment]
Then I'm out of ideas. As it doesn't seem to be a permission issue and the container works without issues with GlusterFS and other network storage I would recommend asking on the galera mailinglist: codership-team@googlegroups.com

**Comment by ghatdev** [comment]
Maybe I should try one more time.
So appreciate for your help!
