### ISSUE TITLE
issue with restart nodes

### ISSUE THREAD

**Issue by alirezaDavid** [adfinis-sygroup/openshift-mariadb-galera#4]
Hi 
when i was restart any node that node those not response.
in logs sync successfully pass with another node.
But it seams user table doesn't created.
enviroment: kubernetes

```
Slave SQL: Error 'Can't find any matching row in the user table' on query. Default database: 'mysql'. Query: 'GRANT ALL PRIVILEGES ON `example_db`.* TO 'example_db'@'%'', Internal MariaDB error code: 1133
```
`mysql-0                           0/1       Running   0          5m`

pods is running but readinessProbe doesn't pass, because user doesn't exists.
I mount path to host.
But when remove host path, pods run without problem.

**Comment by tongpu** [comment]
We've run into this issue too, and it we've just fixed it yesterday. I've tested it on Kubernetes, but still need to check if it behaves the same way on OpenShift. You can test the new image from #5.

**Comment by tongpu** [comment]
We've tested it on OpenShift Origin, and merged it to master.
